import { createPikomonHtml } from "./pikomon.js"

const container = document.querySelector('#container')

//take html cards generated by pikomon.js and display in DOM

container.innerHTML = createPikomonHtml()